# Generated by Django 3.1.1 on 2020-09-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.CharField(choices=[('Tandoori', 'Tandoori'), ('HotnSpicy', 'Hot n Spicy'), ('Chicken', 'Chicken'), ('Pepperoni', 'Pepperoni'), ('Fajita', 'Fajita'), ('AllCheese', 'All Cheese'), ('Margherita', 'Margherita'), ('Veggie', 'Veggie')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default=None, max_length=10),
        ),
    ]
