# Generated by Django 3.1.1 on 2020-09-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_pizza_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
    ]
