# Generated by Django 3.1.1 on 2020-10-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tandoori', 'Tandoori'), ('HotnSpicy', 'Hot n Spicy'), ('Chicken', 'Chicken'), ('Pepperoni', 'Pepperoni'), ('Fajita', 'Fajita'), ('AllCheese', 'All Cheese'), ('Margherita', 'Margherita'), ('Veggie', 'Veggie')], default=None, max_length=10)),
                ('size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default=None, max_length=10)),
            ],
        ),
    ]
